### ISSUE TITLE
API Login/register form requires validation

### ISSUE THREAD

**Issue by kevinfalting** [22arw/megaphone#9]
The register and login routes need to perform validation to ensure good data is being stored in the db.

**Comment by callen5914** [comment]
So this form is on the Angular Side or static side?

**Comment by kevinfalting** [comment]
There are two issues for this. This one is for server-side validation, and #8 is for the front-end validation.

The login form is a static page for now, so you'd have to write some in-line javascript.

**Comment by kevinfalting** [comment]
Validation is performed on the email address to ensure it is a domain we want.

**Comment by kevinfalting** [comment]
Major changes to the app make this issue irrelevant.
